// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebwyjknqolddyedbczjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVid3lqa25xb2xkZHllZGJjemp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MDM2MTIsImV4cCI6MjA2MzQ3OTYxMn0.9juCi44kFoFajrFC6gG5IsEWnK8zJEkJWc9fcWgSUk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);